changelog:
  categories:
    - title: ⚠️ Breaking Changes
      labels:
        - breaking
    - title: 🆕 Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: 🧱 Dependencies
      labels:
        - dependencies
